name: PSAlpaca

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: read-all

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy Local Files
      run: |
        New-Item -ItemType Directory -Path "C:\Program\ Files\WindowsPowerShell\Modules" -Name "PSAlpaca"
        Copy-Item -Path PSAlpaca.psm1 -Destination "C:\Program Files\WindowsPowerShell\Modules\PSAlpaca"
        Copy-Item -Path PSAlpaca.psd1 -Destination "C:\Program Files\WindowsPowerShell\Modules\PSAlpaca"
        Copy-Item -Path private -Recurse -Destination "C:\Program Files\WindowsPowerShell\Modules\PSAlpaca"
        Copy-Item -Path public -Recurse -Destination "C:\Program Files\WindowsPowerShell\Modules\PSAlpaca"
    - name: Import PSAlpaca Module
      run: Import-Module PSAlpaca
    - name: Install Pester 5
      run: |
        $LatestPester = Find-Module -Name Pester
        Get-Module -Name Pester | Where-Object {$_.Version -ne $LatestPester.Version} | ForEach-Object { Uninstall-Module $_ }
        Install-Module Pester -Scope AllUsers -RequiredVersion $LatestPester.Version
