name: PSAlpaca

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: read-all

env:
  PESTER_VERSION: 5.5.0

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy Local Files
      run: Copy-Item . -Destination "C:\Program Files\WindowsPowerShell\Modules\PSAlpaca" -Recurse -Force -Verbose
    - name: Import PSAlpaca Module
      run: Import-Module PSAlpaca
    - name: Install Pester 5
      run: |
        Install-Module Pester -Scope AllUsers -RequiredVersion $LatestPester.Version -Confirm:$false -Force -Verbose
        Get-Module -Name Pester -ListAvailable
    - name: Run Pester Tests with Configuration
      run: |
        Import-Module Pester -RequiredVersion ${{ env.PESTER_VERSION }}
        $configFilePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "PSAlpaca.Tests.Config.psd1"
        $configData = Import-PowerShellDataFile -Path $configFilePath
        $pesterConfig = New-PesterConfiguration @configData
        Invoke-Pester -Configuration $pesterConfig
